version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - './src:/src'
    networks:
      - bridge
    depends_on:
      - soketi
      - mariadb
      - redis
      - meilisearch
      - nginx
  schedule:
    build:
      context: ./app
      dockerfile: Dockerfile
    user: ${UID:-1000}:${GID:-1000}
    working_dir: /src/api
    command: php artisan schedule:work
    volumes:
      - './src:/src'
    networks:
      - bridge
    depends_on:
      - app
  horizon:
    build:
      context: ./app
      dockerfile: Dockerfile
    user: ${UID:-1000}:${GID:-1000}
    working_dir: /src/api
    command: php artisan horizon
    volumes:
      - './src:/src'
    networks:
      - bridge
    depends_on:
      - app
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    user: ${UID:-1000}:${GID:-1000}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '80:8080'
      - '443:4443'
      - '1935:1935'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './nginx/conf.d:/etc/nginx/conf.d:ro'
      - './nginx/config:/etc/nginx/config:ro'
      - './nginx/sites:/etc/nginx/sites:ro'
      - './nginx/ssl:/etc/nginx/ssl:ro'
      - './src:/src:ro'
    networks:
      - bridge
    depends_on:
      - soketi
  mariadb:
    image: mariadb:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mariadb:/var/lib/mysql'
    networks:
      - bridge
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
    networks:
      - bridge
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
  meilisearch:
    image: 'getmeili/meilisearch:latest'
    ports:
      - '7700:7700'
    volumes:
      - 'meilisearch:/meili_data'
    networks:
      - bridge
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
      retries: 3
      timeout: 5s
  soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    environment:
      DEBUG: '1'
      METRICS_SERVER_PORT: '9601'
    ports:
      - '6001:6001'
      - '9601:9601'
    networks:
      - bridge
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - bridge
networks:
  bridge:
    driver: bridge
volumes:
  mariadb:
    driver: local
  redis:
    driver: local
  meilisearch:
    driver: local
  soketi:
    driver: local
