version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - './src:/src'
    networks:
      - bridge
    depends_on:
      - mariadb
      - nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    user: ${UID:-1000}:${GID:-1000}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '80:8080'
      - '443:4443'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './nginx/conf.d:/etc/nginx/conf.d:ro'
      - './nginx/config:/etc/nginx/config:ro'
      - './nginx/sites:/etc/nginx/sites:ro'
      - './nginx/ssl:/etc/nginx/ssl:ro'
      - './src:/src:ro'
    networks:
      - bridge
  mariadb:
    image: mariadb:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mariadb:/var/lib/mysql'
    networks:
      - bridge
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - bridge
networks:
  bridge:
    driver: bridge
volumes:
  mariadb:
    driver: local
